### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by chaals** [w3ctag/eme#2]
I don't think the biggest issue is about blocking compositing, because it seems that platforms can do this, and if they can't, the relevant content can usually be rendered "side by side" with no real problems.

On the other hand, the ability to use third-party content which is protected by a different system is important. This is really just a refinement of the whole issue of content being available on different platforms, but where a user requires e.g. sign-language interpretation for video (which costs money to produce, and may not be provided except under commercial terms - the same as content which is being protected), the inability to use CDMs for both kinds of content becomes an accessibility issue, IMHO.

**Comment by cynthia** [comment]
The TAG is not working on EME (and in particular this document) anymore, and any further issues should be brought up with the working group.
