### ISSUE TITLE
DRM is for restricting use of information not restricted access to information

### ISSUE THREAD

**Issue by ghost** [w3ctag/eme#3]
The introduction discusses restricting access to information, and gives some examples, but concludes that this will 'inform the debate about the inclusion of Encrypted Media Extensions (EME) in HTML'.  The purpose of EME DRM is to restrict use of information and not to restrict access to information so this only confuses the 'debate'.

The introduction and discussion should focus on technology that restricts the use of information by the authorized recipient if it wants to be relevant to DRM.

To 'share information with restricted groups of people' does not demand restricting what they can do with the information.

'to protect our privacy, it should be possible to share information that no one can see aside from the intended recipients'  also does not demand restricting what they can do with the information.

'And because of this need for privacy, the web needs to also be secure and trustworthy.'  again this does not demand restricting what the authorized recipient can do with the information.

> Over the web's 25 years there have been several technologies and architectures which have had the effect of restricting access for some people to portions of the web.

Again, you confuse 'restricting access for some people to portions of the web' with restricting what the authorized recipient can do with the information.

Perhaps you mean:
'Over the web's 25 years there have been several technologies and architectures which have had the effect of restricting how the authorized recipient of information accessed over the web can use the information.'

> This document explores how these work and the effect they had on the web, with the ultimate goal of aiming to inform the debate about the inclusion of Encrypted Media Extensions (EME) in HTML.

'how these work and the effect they had on the web' is not even relevant to DRM so it is not possible that it can ' inform the debate about the inclusion of Encrypted Media Extensions (EME) in HTML.'

**Comment by cynthia** [comment]
The TAG is not working on EME (and in particular this document) anymore, and any further issues should be brought up with the working group.
