### ISSUE TITLE
Limiting the lifetime of content is a use case for DRM on the web.

### ISSUE THREAD

**Issue by ghost** [w3ctag/eme#4]
'Content with a limited lifetime is contrary to the best interests of consumers of that content.'

A use of DRM is to restrict the number of times content can be viewed.  Even if 'platform independence' were possible then it would still conflict with this use of DRM, so these points do not support 'platform independence' for DRM.

**Comment by cynthia** [comment]
The TAG is not working on EME (and in particular this document) anymore, and any further issues should be brought up with the working group.
